/**
 * Copyright (C) 2001-2017 by RapidMiner and the contributors
 * 
 * Complete list of developers available at our web site:
 * 
 * http://rapidminer.com
 * 
 * This program is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see http://www.gnu.org/licenses/.
*/
package com.rapidminer.operator.nio.model;

import com.rapidminer.example.Attributes;
import com.rapidminer.operator.ports.metadata.AttributeMetaData;

import java.util.Observable;
import java.util.Observer;


/**
 * The meta data either guessed by RapidMiner or specified by the user for a column of an excel
 * file, csv file, etc.
 *
 * @author Simon Fischer
 */
public class ColumnMetaData extends Observable {

	/** Attribute name as specified in the file, or generated by the source. */
	private String originalAttributeName;
	/** Attribute name as specified by the user. */
	private String userDefinedAttributeName;
	private int attributeValueType;
	private String role;
	private boolean selected;

    /**
     * Instantiates a new Column meta data.
     */
    public ColumnMetaData() {

	}

    /**
     * Instantiates a new Column meta data.
     *
     * @param originalAttributeName    the original attribute name
     * @param userDefinedAttributeName the user defined attribute name
     * @param attributeValueType       the attribute value type
     * @param role                     the role
     * @param selected                 the selected
     */
    public ColumnMetaData(String originalAttributeName, String userDefinedAttributeName, int attributeValueType,
			String role, boolean selected) {
		super();
		this.originalAttributeName = originalAttributeName;
		this.userDefinedAttributeName = userDefinedAttributeName;
		this.attributeValueType = attributeValueType;
		this.role = role;
		this.selected = selected;
	}

	/** Used to inform the validator about the ColumnMetaData object **/
	@Override
	public synchronized void addObserver(Observer o) {
		super.addObserver(o);
	}

    /**
     * Gets original attribute name.
     *
     * @return the original attribute name
     */
    public String getOriginalAttributeName() {
		return originalAttributeName;
	}

    /**
     * Sets original attribute name.
     *
     * @param originalAttributeName the original attribute name
     */
    public void setOriginalAttributeName(String originalAttributeName) {
		if (equals(this.originalAttributeName, originalAttributeName)) {
			return;
		}
		this.originalAttributeName = originalAttributeName;
		setChanged();
		notifyObservers();
	}

    /**
     * Gets user defined attribute name.
     *
     * @return the user defined attribute name
     */
    public String getUserDefinedAttributeName() {
		return userDefinedAttributeName;
	}

    /**
     * Sets user defined attribute name.
     *
     * @param userDefinedAttributeName the user defined attribute name
     */
    public void setUserDefinedAttributeName(String userDefinedAttributeName) {
		if (equals(this.userDefinedAttributeName, userDefinedAttributeName)) {
			return;
		}
		this.userDefinedAttributeName = userDefinedAttributeName;
		setChanged();
		notifyObservers();
	}

    /**
     * Gets attribute value type.
     *
     * @return the attribute value type
     */
    public int getAttributeValueType() {
		return attributeValueType;
	}

    /**
     * Sets attribute value type.
     *
     * @param attributeValueType the attribute value type
     */
    public void setAttributeValueType(int attributeValueType) {
		if (attributeValueType == this.attributeValueType) {
			return;
		}
		this.attributeValueType = attributeValueType;
		setChanged();
		notifyObservers();
	}

    /**
     * Gets role.
     *
     * @return the role
     */
    public String getRole() {
		return role;
	}

    /**
     * Sets role.
     *
     * @param role the role
     */
    public void setRole(String role) {
		if (equals(role, this.role)) {
			return;
		}
		this.role = role;
		setChanged();
		notifyObservers();
	}

    /**
     * Is selected boolean.
     *
     * @return the boolean
     */
    public boolean isSelected() {
		return selected;
	}

    /**
     * Sets selected.
     *
     * @param selected the selected
     */
    public void setSelected(boolean selected) {
		this.selected = selected;
		setChanged();
		notifyObservers();
	}

	@Override
	public String toString() {
		return getRole() + " " + getUserDefinedAttributeName() + " (" + getOriginalAttributeName() + ")"
				+ getAttributeValueType() + " " + (isSelected() ? "x" : "-");
	}

    /**
     * Gets attribute meta data.
     *
     * @return the attribute meta data
     */
    public AttributeMetaData getAttributeMetaData() {
		String roleId = getRole();
		if (!Attributes.ATTRIBUTE_NAME.equals(roleId)) {
			return new AttributeMetaData(getUserDefinedAttributeName(), getAttributeValueType(), roleId);
		} else {
			return new AttributeMetaData(getUserDefinedAttributeName(), getAttributeValueType());
		}
	}

    /**
     * Returns whether the user specified a name different from the default.  @return the boolean
     *
     * @return the boolean
     */
    public boolean isAttributeNameSpecified() {
		if (userDefinedAttributeName == null) {
			return false;
		}
		return !userDefinedAttributeName.equals(originalAttributeName);
	}

	private static boolean equals(String s1, String s2) {
		return ((s1 == null) && (s2 == null)) || ((s1 != null) && s1.equals(s2));
	}
}
